### ISSUE TITLE
[Substack] Author names containing 'and' get split into two authors

### ISSUE THREAD

**Issue by dennis-dean** [TryGhost/migrate#1087]
In the current version, names containing 'and' (i.e. Brandon or Fernando) get split into two authors ('Br' and 'on' / 'Fern' and 'o'). 

Confirmed changing this line:

`let authorSplit = author.split(/(?:,|and|&)+/).map(function (item) {`

to 

`let authorSplit = author.split(/\s*(?:,\s| and | & )\s*/).map(function (item) {`

fixes the issue.

**Comment by PaulAdamDavis** [comment]
Hey @dennis-dean, great spot, and thank you! Fixed pushed with you as a co-author.
