### ISSUE TITLE
Error importing from Substack

### ISSUE THREAD

**Issue by fredkelly** [TryGhost/migrate#360]
I'm using the migrate command to convert my Substack export for Ghost:
```migrate substack posts.csv --email XXX@YYY.ZZZ --url https://XXX.substack.com --readPosts posts --drafts false --verbose```

The process runs with no errors (it's only a couple of posts) generating a `gh-posts-XXX.zip` file. However, when I try to import this into Ghost (self-hosted using the DigitalOcean Droplet), I get this error:
<img width="1273" alt="Screenshot 2021-08-24 at 17 02 56" src="https://user-images.githubusercontent.com/325322/130643063-040b4476-276c-47c5-b586-30c295c34b0c.png">

I've tried importing another Ghost generated export and this works fine so I'm fairly confident the issue is with the generation of the JSON file. Can anyone suggest a remedy?

**Comment by PaulAdamDavis** [comment]
I believe this was an issue with Ghost itself, where it had an invalid default for the new `email_only` property of a post object when importing content.

Ghost v4.13.0 contains [the fix](https://github.com/TryGhost/Ghost/commit/90a4d369db1f5cd0961ee92cd3e92d7badaeaf15).
