### ISSUE TITLE
Unable to scrape URL

### ISSUE THREAD

**Issue by wbhob** [TryGhost/migrate#386]
I've got a sub stack URL with almost 900 posts and a custom domain. When I try to run the migration tool, it starts failing and saying "Unable to scrape URL". 

My hunch is this may be because of rate limiting, so making this a background process with a delay between requests may make this more stable. Happy to debug one-on-one to give more context!

**Comment by PaulAdamDavis** [comment]
Hi @wbhob! This has now been fixed. Scraping meta data was hitting a rate limit which is now accounted for. Scraping will be much slower, but now error-free.

**Comment by PaulAdamDavis** [comment]
@wbhob This fix is now released in 0.22.0
