### ISSUE TITLE
Import of blog post images

### ISSUE THREAD

**Issue by philipschilling** [TryGhost/migrate#415]
When I use the migration tool to import blog posts from Medium to Ghost, the image URLs still point to Medium's cloud storage provider rather than importing the images itself to be hosted on the Ghost server. The images are not part of the zip archive when you do an export on Medium.

Is that intended and would I need to upload each image manually via Ghost to be hosted on the same Ghost server? Another way would be that I upload the images to the Ghost content directory and change the URLs manually in all exported blog post HTML files from Medium before I run the migration command. Is there any easier way to solve this?

**Comment by PaulAdamDavis** [comment]
I believe this is related to #414. If an image cannot be downloaded or accessed in the file system, it will not change the path in the resulting JSON file, so it may be a permissions issue.

**Comment by PaulAdamDavis** [comment]
I've done several Medium migrations since this issue, and have not had issues with image URLs not being updated. If this crops up again, please re-open this issue.
