### ISSUE TITLE
Jekyll: support importing  `basename`

### ISSUE THREAD

**Issue by markstos** [TryGhost/migrate#504]
It's great to not break or change URLs when possible, and importing `permalink` and `basename` will help with that. 

In my config, I have `permalink` and `basename` defined for nearly all my posts, by my Jekyll blog was in turn migrated from Movable Type, and explicitly importing those helped me not break the URLs during the /last/ platform transition.

Thanks!

**Comment by markstos** [comment]
I discovered that the "scraping" phase of importing can fail due to this issue. That's because the importer assumes it can construct a correct source URL for the posts, but it can't necessarily get it right if the `permalink` has changed.

**Comment by markstos** [comment]
I'm working on converting Jekyll's `basename` to Ghost's `slug`.

**Comment by markstos** [comment]
I'm narrowing the scope of this issue to only cover `basename`, which I've fixed in the linked commit above. A new issue could be opened for supporting `permalink`, but I'm not sure I need it for my personal migration so I"m not sure I'll implement it.

**Comment by PaulAdamDavis** [comment]
Hey @markstos! I just wanted to quickly say thanks for all of your issues and PRs! I'm going to slowly work my way through them.

**Comment by markstos** [comment]
Thanks @PaulAdamDavis. Based on the few mentions of Jekyll in the forum and the state of the migration tool, it seems there aren't a lot of people coming to Ghost from Jekyll, so I understand if this work isn't at the top of the priority list.
