### ISSUE TITLE
Jekyll: Using --scrape=none still results in scraping

### ISSUE THREAD

**Issue by markstos** [TryGhost/migrate#515]
To avoid bugs in the web scraping phase of the Jekyll importer, I tried using the `--scrape=none` option documented in the README. In the output, it didn't claim to being doing any scraping after this, but the resulting `.zip` produced includes a number of photos downloaded from Flicker, a few photos hosted by the blog itself and an audio file that got scraped as well. 

I'm not sure where this bug is. The `mg-jekyll-export` does not directly call this code.

In the case of the images scraped from Flickr,  there's no easy way undo this, since the URLs in the HTML must have been updated to be local URLs instead of absolute.

**Comment by PaulAdamDavis** [comment]
I believe this is no longer an issue, so I'll close until I hear otherwise.
