### ISSUE TITLE
unable to import tags from medium export

### ISSUE THREAD

**Issue by vaidik** [TryGhost/migrate#517]
I recently tried to import all my posts from medium into my local ghost installation. While I was able to import all the posts, none of the posts had any tags created. The only tag that was set on each post was `#medium`.

It would be nice if the tags were also imported after using `migrate medium ...` command to generate the Ghost friendly zip and importing it.

**Comment by yekta** [comment]
Same for me too, this would be a nice addition.

**Comment by Assilfira** [comment]
Hello.

I faced the same issue, therefore I've created the following Merge Request: https://github.com/TryGhost/migrate/pull/680

It worked for me.

Best regards,
Nuno

**Comment by PaulAdamDavis** [comment]
Solved with https://github.com/TryGhost/migrate/commit/e11e54b83b68cd20815bd9571ac0a6464a9ffa12
