### ISSUE TITLE
set canonical URL on importing posts from medium

### ISSUE THREAD

**Issue by vaidik** [TryGhost/migrate#518]
This is a feature request.

I have a use-case where I want to create my new blog on ghost while keeping my medium posts around as well. To avoid search engines from penalising my site, I want to make sure that when I import all the posts from medium into ghost (using `migrate medium` utility) the canonical URL is set to the original post on published on medium.

**Comment by PaulAdamDavis** [comment]
As of version `0.30.20`, this is now possible by passing `--mediumAsCanonical true` as an option.
