### ISSUE TITLE
Substack - Process content fails

### ISSUE THREAD

**Issue by talvasconcelos** [TryGhost/migrate#665]
With or without scraping, i only get the metadata from the posts, not the content! It doesn't event construct the .zip. I see the info in the `/tmp/mg` folder.

Any clues?

**Comment by PaulAdamDavis** [comment]
Hi @talvasconcelos, I've just tested this `migrate substack --url https://example.com --pathToZip /path/to/export.zip` with the latest version `0.30.12` and it works for me. Can you share the command you ran, and any output from the terminal?

**Comment by PaulAdamDavis** [comment]
@nodeteamdev Fixed

I'm going to close this as it's been a while. Please open a new issue if you have any problems!
